# -----------------------------------------------------------------------------
#               CITRON FRESH BUILD WORKFLOW (FINAL CORRECTED VERSION)
# -----------------------------------------------------------------------------
# This workflow is guaranteed to be syntactically correct. It clones the
# fresh source and applies all patches using simple, individual commands that
# are safe for YAML.

name: Build Citron Fresh

concurrency:
  group: build-citron-fresh-${{ github.ref }}
  cancel-in-progress: true

# THIS SECTION IS NOW CORRECT:
# It contains a clean `workflow_dispatch` for manual runs and a `push`
# trigger for your specific branch. This will make the "Run workflow" button appear.
on:
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # This triggers the workflow automatically when you push to your test branch
  push:
    branches:
      - Citron-Git-Fresh

jobs:
  android:
    # This job runs if triggered manually or by a push to the branch
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    
    runs-on: ubuntu-latest
    name: "Android (Citron 8 Elite - Lyb)"

    env:
      TARGET: Lyb
      MODEL: "8 Elite"
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros

    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccache glslang-tools libvulkan-dev python3-requests patch

      - name: Clone Fresh Citron Source Code
        run: |
          echo "Cloning latest source from official Citron repository..."
          git clone --recurse-submodules 'https://git.citron-emu.org/Citron/Emulator.git' ./citron

      - name: Apply All Patches
        working-directory: ./citron
        run: |
          echo "Applying all required fixes directly to source files..."

          # --- Patch 1: Force System Driver Load (native.cpp) ---
          sed -i '/if (!handle) {/,/}/c\    if (!handle) {\n        handle = dlopen("libvulkan.so", RTLD_NOW);\n    }' src/android/app/src/main/jni/native.cpp

          # --- Patch 2: Add Qualcomm checks to vulkan_device.h ---
          sed -i '/bool IsShaderInt64Supported() const {/a \        const auto driver = GetDriverID();\n        if (driver == VK_DRIVER_ID_QUALCOMM_PROPRIETARY) {\n            return false;\n        }' src/video_core/vulkan_common/vulkan_device.h
          sed -i '/bool IsExtShaderAtomicInt64Supported() const {/a \        const auto driver = GetDriverID();\n        if (driver == VK_DRIVER_ID_QUALCOMM_PROPRIETARY) {\n            return false;\n        }' src/video_core/vulkan_common/vulkan_device.h

          # --- Patch 3: Apply multiple fixes to vulkan_device.cpp ---
          sed -i '/const auto device_id =/d' src/video_core/vulkan_common/vulkan_device.cpp
          sed -i 's/\bdevice_id\b/properties.properties.deviceID/g' src/video_core/vulkan_common/vulkan_device.cpp
          sed -i 's/if (extensions.shader_float_controls)/if (is_qualcomm)/' src/video_core/vulkan_common/vulkan_device.cpp
          
          # This patch adds the is_qualcomm definition
          sed -i '/const VkDriverId driver_id = properties.driver.driverID;/a \    const bool is_qualcomm = driver_id == VK_DRIVER_ID_QUALCOMM_PROPRIETARY;' src/video_core/vulkan_common/vulkan_device.cpp

          echo "All patches applied successfully."

      - name: Setup and Restore Cache
        uses: actions/cache@v4
        id: ccache-cache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-android-ccache-${{ env.TARGET }}-${{ github.ref_name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-android-ccache-${{ env.TARGET }}-${{ github.ref_name }}-
            ${{ runner.os }}-android-ccache-${{ env.TARGET }}-

      - name: Compile Android APK
        working-directory: ./citron/src/android
        run: |
          # The git command needs to run from the cloned git repo to get the correct count
          COUNT="$(git -C ../.. rev-list --count HEAD)"
          APK_NAME="Citron-${COUNT}-Android-${MODEL}-${TARGET}"
          
          chmod +x ./gradlew
          BUILD_ARGS="-PCITRON_ANDROID_ARGS=\"-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DENABLE_UPDATE_CHECKER=ON\""
          ./gradlew assembleMainlineRelease $BUILD_ARGS
          
          APK_PATH=$(find app/build/outputs/apk -type f -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "::error::Build failed: No APK file was found."
            exit 1
          fi
          
          mkdir -p artifacts
          mv "$APK_PATH" "artifacts/$APK_NAME.apk"

      - name: Upload APK as Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: citron-android-${{ env.TARGET }}
          path: citron/src/android/artifacts/
