# -----------------------------------------------------------------------------
#               CITRON UNIFIED SYNC AND BUILD WORKFLOW
# -----------------------------------------------------------------------------
# This single workflow file handles everything:
# 1. Syncs your 'main' branch with the official Citron repository.
# 2. Builds the Android APK from your newly synced code.
# 3. Applies all your custom patches (8 Elite, System Driver, etc.)
#    directly during the build process without needing patch files.

name: Sync and Build Citron

concurrency:
  group: sync-and-build-citron-${{ github.ref }}
  cancel-in-progress: true

on:
  # This allows you to run the entire sync and build process manually from the Actions tab.
  workflow_dispatch:

jobs:
  # JOB 1: Sync your fork with the upstream Citron repository.
  sync:
    runs-on: ubuntu-latest
    name: "Sync with Upstream Citron"
    steps:
      - name: Checkout Your Fork
        uses: actions/checkout@v4
        with:
          # We need to fetch the full history to sync correctly.
          fetch-depth: 0

      - name: Sync Fork with Upstream
        uses: upstream-sync/fork-sync@v1
        with:
          # The official Citron GitHub repository to sync from.
          repo: citron-emu/citron
          # The branch in your fork to update.
          target: main
          # The branch in the official repo to pull from.
          source: main
          # Use the default GitHub token to perform the sync.
          token: ${{ secrets.GITHUB_TOKEN }}

  # JOB 2: Build the Android APK after the sync is complete.
  build:
    # This is crucial: The 'build' job will only start after the 'sync' job succeeds.
    needs: sync
    runs-on: ubuntu-latest
    name: "Build Android (Citron 8 Elite - Lyb)"

    env:
      TARGET: Lyb
      MODEL: "8 Elite"
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros

    steps:
      - name: Checkout Synced Source Code
        uses: actions/checkout@v4
        with:
          # This checks out YOUR fork's code, which now includes the latest updates from the sync job.
          fetch-depth: 0
          submodules: recursive

      - name: Install Build Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccache glslang-tools libvulkan-dev python3-requests patch

      - name: Apply All Patches (Robust Sed Method)
        run: |
          echo "Applying all required fixes directly to the checked-out source code..."

          # --- Patch 1: Force System Driver Load (native.cpp) ---
          sed -i '/if (!handle) {/,/}/c\    if (!handle) {\n        handle = dlopen("libvulkan.so", RTLD_NOW);\n    }' src/android/app/src/main/jni/native.cpp

          # --- Patch 2: 8 Elite Fixes for Qualcomm (vulkan_device.h) ---
          sed -i '/bool IsShaderInt64Supported() const {/a \        const auto driver = GetDriverID();\n        if (driver == VK_DRIVER_ID_QUALCOMM_PROPRIETARY) {\n            return false;\n        }' src/video_core/vulkan_common/vulkan_device.h
          sed -i '/bool IsExtShaderAtomicInt64Supported() const {/a \        const auto driver = GetDriverID();\n        if (driver == VK_DRIVER_ID_QUALCOMM_PROPRIETARY) {\n            return false;\n        }' src/video_core/vulkan_common/vulkan_device.h

          # --- Patch 3: 8 Elite & Cleanup Fixes (vulkan_device.cpp) ---
          sed -i '/const auto device_id =/d' src/video_core/vulkan_common/vulkan_device.cpp
          sed -i 's/\bdevice_id\b/properties.properties.deviceID/g' src/video_core/vulkan_common/vulkan_device.cpp
          sed -i 's/if (extensions.shader_float_controls)/if (is_qualcomm)/' src/video_core/vulkan_common/vulkan_device.cpp
          sed -i '/const VkDriverId driver_id = properties.driver.driverID;/a \    const bool is_qualcomm = driver_id == VK_DRIVER_ID_QUALCOMM_PROPRIETARY;' src/video_core/vulkan_common/vulkan_device.cpp

          echo "All patches applied successfully."

      - name: Setup and Restore Cache
        uses: actions/cache@v4
        id: ccache-cache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-android-ccache-${{ env.TARGET }}-${{ github.ref_name }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-android-ccache-${{ env.TARGET }}-${{ github.ref_name }}-

      - name: Compile Android APK
        working-directory: ./src/android
        run: |
          COUNT="$(git rev-list --count HEAD)"
          APK_NAME="Citron-${COUNT}-Android-${MODEL}-${TARGET}"
          
          chmod +x ./gradlew
          BUILD_ARGS="-PCITRON_ANDROID_ARGS=\"-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DENABLE_UPDATE_CHECKER=ON\""
          ./gradlew assembleMainlineRelease $BUILD_ARGS
          
          APK_PATH=$(find app/build/outputs/apk -type f -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "::error::Build failed: No APK file was found."
            exit 1
          fi
          
          mkdir -p artifacts
          mv "$APK_PATH" "artifacts/$APK_NAME.apk"

      - name: Upload APK as Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: citron-android-${{ env.TARGET }}
          path: src/android/artifacts/
